### ISSUE TITLE
Unregister receiver.

### ISSUE THREAD

**Issue by jmimohsin** [payu-intrepos/Android-SDK-Sample-App#18]
This is my logcat error:-

Activity com.payu.payuui.PaymentsActivity has leaked IntentReceiver com.payu.custombrowser.Bank$6@399f3674 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                    android.app.IntentReceiverLeaked: Activity com.payu.payuui.PaymentsActivity has leaked IntentReceiver com.payu.custombrowser.Bank$6@399f3674 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1085)
                                                                        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:850)
                                                                        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1755)
                                                                        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1735)
                                                                        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1729)
                                                                        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:489)
                                                                        at com.payu.payuui.PaymentsActivity$1.registerBroadcast(PaymentsActivity.java:121)
                                                                        at com.payu.custombrowser.Bank.prepareSmsListener(Bank.java:617)
                                                                        at com.payu.custombrowser.Bank.getInitializeJS(Bank.java:1153)
                                                                        at com.payu.custombrowser.Bank.onCreate(Bank.java:476)
                                                                        at android.support.v4.app.Fragment.performCreate(Fragment.java:1766)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:917)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
                                                                        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
                                                                        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
                                                                        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
                                                                        at android.app.Activity.performStart(Activity.java:6113)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2341)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2440)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:162)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5430)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by chakricb** [comment]
Try to call the PaymentsActivity from an intermediate activity. This should fix your problem.
