### ISSUE TITLE
exception in NumberPicker

### ISSUE THREAD

**Issue by sarathraj-coder** [payu-intrepos/Android-SDK-Sample-App#36]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.NumberPicker.setMinValue(int)' on a null object reference
                                                                                       at com.payu.payuui.Widget.MonthYearPickerDialog.onCreateDialog(MonthYearPickerDialog.java:41)
                                                                                       at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:312)
                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                                                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
                                                                                       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:541)
                                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by sarathraj-coder** [comment]
This is in android 23
