### ISSUE TITLE
PayuResponse: Error in Parcelable implementation

### ISSUE THREAD

**Issue by mvij** [payu-intrepos/Android-SDK-Sample-App#42]
The com.payu.india.Model.PayuResponse class is missing code in its Parcelable implementation.

The constructor is reading PayuEmiAmountAccordingToInterest

```
    protected PayuResponse(Parcel in) {
        storedCards = in.createTypedArrayList(StoredCard.CREATOR);
        emi = in.createTypedArrayList(Emi.CREATOR);
        creditCard = in.createTypedArrayList(PaymentDetails.CREATOR);
        debitCard = in.createTypedArrayList(PaymentDetails.CREATOR);
        netBanks = in.createTypedArrayList(PaymentDetails.CREATOR);
        cashCard = in.createTypedArrayList(PaymentDetails.CREATOR);
        ivr = in.createTypedArrayList(PaymentDetails.CREATOR);
        ivrdc = in.createTypedArrayList(PaymentDetails.CREATOR);
        paisaWallet = in.createTypedArrayList(PaymentDetails.CREATOR);
        lazyPay = in.createTypedArrayList(PaymentDetails.CREATOR);
        responseStatus = in.readParcelable(PostData.class.getClassLoader());
        cardInformation = in.readParcelable(CardInformation.class.getClassLoader());
        payuOffer = in.readParcelable(PayuOffer.class.getClassLoader());
        transactionDetailsList = in.createTypedArrayList(TransactionDetails.CREATOR);
        offerDetailsList = in.createTypedArrayList(PayuOffer.CREATOR);
        payuEmiAmountAccordingToInterest = in.readParcelable(PayuEmiAmountAccordingToInterest.class.getClassLoader());
        payuOfferDetails = in.readParcelable(PayuOfferDetails.class.getClassLoader());
    }
```

but `writeToParcel` is missing write statement.

```
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeTypedList(storedCards);
        dest.writeTypedList(emi);
        dest.writeTypedList(creditCard);
        dest.writeTypedList(debitCard);
        dest.writeTypedList(netBanks);
        dest.writeTypedList(cashCard);
        dest.writeTypedList(ivr);
        dest.writeTypedList(ivrdc);
        dest.writeTypedList(paisaWallet);
        dest.writeTypedList(lazyPay);
        dest.writeParcelable(responseStatus, flags);
        dest.writeParcelable(cardInformation, flags);
        dest.writeParcelable(payuOffer, flags);
        dest.writeTypedList(transactionDetailsList);
        dest.writeTypedList(offerDetailsList);
        dest.writeParcelable(payuOfferDetails, flags);
    }
```

I'm facing the following crash 

```
E/AndroidRuntime: FATAL EXCEPTION: main
   Process: com.healthifyme.basic, PID: 7693
   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.healthifyme.basic/com.healthifyme.basic.payment.PaymentActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android:fragments
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6165)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android:fragments
    at android.os.Parcel.readParcelableCreator(Parcel.java:2536)
    at android.os.Parcel.readParcelable(Parcel.java:2462)
    at com.payu.india.Model.PayuResponse.<init>(PayuResponse.java:135)
    at com.payu.india.Model.PayuResponse$1.createFromParcel(PayuResponse.java:57)
    at com.payu.india.Model.PayuResponse$1.createFromParcel(PayuResponse.java:54)
    at android.os.Parcel.readParcelable(Parcel.java:2471)
    at android.os.Parcel.readValue(Parcel.java:2365)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
    at android.os.BaseBundle.unparcel(BaseBundle.java:269)  
    at android.os.BaseBundle.getBoolean(BaseBundle.java:731)
    at android.app.Activity.restoreHasCurrentPermissionRequest(Activity.java:6928)
    at android.app.Activity.performCreate(Activity.java:6686)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743) 
    at android.app.ActivityThread.-wrap12(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6165) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by himgupta229** [comment]
Please check on version 4.4.4 of PayuSDK [https://github.com/payu-intrepos/Android-SDK/releases/tag/4.4.4](url)
