### ISSUE TITLE
Crash in GenericIntent Tab

### ISSUE THREAD

**Issue by sachin-sivadasan** [payu-intrepos/Android-SDK-Sample-App#57]
I am getting crash reports from app while users using payment gateway. The one way i can reproduce this issue is given below. The actual scenario is not identified yet but the crash log is same.

**Scenario**
1. Go to Generic Intent Screen.
2. Click "PAY NOW" button and it will show available apps in device.
3. Press device home button(now app will go to background).
4. After that you will get crash most of the time(otherwise try open app from history).

`2019-12-11 22:22:21.942 3879-3879/com.payu.testapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.payu.testapp, PID: 3879
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 587876 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.os.TransactionTooLargeException: data parcel size 587876 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1129)
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4027)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6692) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) `

**Comment by himgupta229** [comment]
Will be handled in next release.

**Comment by sachin-sivadasan** [comment]
@himgupta229  is it fixed in the latest release v4.4.8?

**Comment by sumit007** [comment]
@himgupta229, We are getting this frequently. Kindly let us know this issue is fixed or not.

**Comment by himgupta229** [comment]
> @himgupta229, We are getting this frequently. Kindly let us know this issue is fixed or not.

Kindly update to below sdk versions in sdkui's build.gradle.

`implementation 'com.payu.phonepe:phonepe-intent:1.5.1'`
`implementation 'com.payu.upisdk:upisdk:1.1.2'`
`implementation 'com.payu.custombrowser:payu-custom-browser:7.6.1'`
`implementation 'com.payu.gpay:payu-gpay:1.3.2' `
